# Generated by Django 4.0.6 on 2022-07-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='signup_date',
            new_name='created_on',
        ),
    ]
