# Generated by Django 4.0.6 on 2022-07-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_signup_date_signup_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=120),
            preserve_default=False,
        ),
    ]
